MONGODB_HOST = "localhost"
MONGODB_PORT = 17017
MONGODB_ADMINUSERNAME = "root"
MONGODB_ADMINPASSWORD = "mymogopassword"

MONGODB_URI = f"mongodb://{MONGODB_ADMINUSERNAME}:{MONGODB_ADMINPASSWORD}@{MONGODB_HOST}:{MONGODB_PORT}"
